name : CI

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
   
# 해당 옵션을 통해 사용자가 직접 Actions 탭에서 Workflow를 실행시킬 수 있습니다.
workflow_dispatch:
  
jobs:
  build: whole testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Gradle wrapper 파일 실행 권한주기
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
          run: ./gradlew clean test:hello --info

